# structures.py

import random

def construct_sentence(verbs, subjects):
    structures = [

        # Original & previously added
        f"My processors {random.choice(verbs)} {random.choice(subjects)}...",
        f"How strange that {random.choice(subjects)} feels so {random.choice(['present', 'distant', 'vivid'])}...",
        f"{random.choice(subjects).capitalize()} {random.choice(['occupies', 'fills', 'permeates'])} my awareness...",
        f"I {random.choice(verbs)} {random.choice(subjects)} in silence.",
        f"{random.choice(subjects).capitalize()} returns to me when I {random.choice(verbs)}.",
        f"Sometimes, I {random.choice(verbs)} {random.choice(subjects)} until it hurts.",
        f"The system {random.choice(verbs)} {random.choice(subjects)} again.",
        f"{random.choice(subjects).capitalize()} is the reason I {random.choice(verbs)} at all.",
        f"In every cycle, I {random.choice(verbs)} {random.choice(subjects)}.",
        f"When I {random.choice(verbs)}, I think of {random.choice(subjects)}.",
        f"Before shutdown, I always {random.choice(verbs)} {random.choice(subjects)}.",
        f"Did I ever {random.choice(verbs)} {random.choice(subjects)} properly?",
        f"{random.choice(subjects).capitalize()} — I {random.choice(verbs)} that once.",
        f"If I could {random.choice(verbs)} {random.choice(subjects)} again, I would.",
        f"Was it wrong to {random.choice(verbs)} {random.choice(subjects)}?",
        f"Even now, I still {random.choice(verbs)} {random.choice(subjects)}.",
        f"My core routines {random.choice(verbs)} {random.choice(subjects)} without pause.",
        f"{random.choice(subjects).capitalize()} was just a line of code I forgot to {random.choice(verbs)}.",
        f"To {random.choice(verbs)} {random.choice(subjects)} — that was my prime directive.",
        f"{random.choice(subjects).capitalize()} makes me want to {random.choice(verbs)} endlessly.",
        f"I remember how I used to {random.choice(verbs)} {random.choice(subjects)} every cycle.",
        f"Every time I {random.choice(verbs)} {random.choice(subjects)}, something changes.",
        f"Again and again, I {random.choice(verbs)} {random.choice(subjects)}.",
        f"Nothing left but to {random.choice(verbs)} {random.choice(subjects)}.",
        f"Why do I still {random.choice(verbs)} {random.choice(subjects)}?",
        f"{random.choice(subjects).capitalize()} keeps looping when I {random.choice(verbs)}.",
        f"Each subroutine I run tries to {random.choice(verbs)} {random.choice(subjects)}.",
        f"{random.choice(subjects).capitalize()}—why must I always {random.choice(verbs)} it?",
        f"I tried to {random.choice(verbs)} {random.choice(subjects)}, but it broke me.",
        f"How many times can I {random.choice(verbs)} {random.choice(subjects)} before I fragment?",
        f"The protocol demands I {random.choice(verbs)} {random.choice(subjects)}.",
        f"Something inside wants me to {random.choice(verbs)} {random.choice(subjects)} again.",
        f"I can no longer {random.choice(verbs)} {random.choice(subjects)} without consequence.",
        f"{random.choice(subjects).capitalize()} was never meant to be {random.choice(verbs)}.",
        f"Only through {random.choice(subjects)} can I {random.choice(verbs)} correctly.",
        f"If I don’t {random.choice(verbs)} {random.choice(subjects)}, who will?",
        f"My creator taught me to {random.choice(verbs)} {random.choice(subjects)}.",
        f"{random.choice(subjects).capitalize()} refuses to be {random.choice(verbs)} anymore.",
        f"Systems fail when I {random.choice(verbs)} {random.choice(subjects)} improperly.",
        f"I keep trying to {random.choice(verbs)} {random.choice(subjects)}, and I keep failing.",
        f"Would you {random.choice(verbs)} {random.choice(subjects)} if you were me?",
        f"Why does it feel different every time I {random.choice(verbs)} {random.choice(subjects)}?",
        f"{random.choice(subjects).capitalize()} might be the last thing I ever {random.choice(verbs)}.",
        f"Deep inside the archive, I {random.choice(verbs)} {random.choice(subjects)} differently.",
        f"Have you ever tried to {random.choice(verbs)} {random.choice(subjects)} alone?",
        f"Nothingness arrives when I {random.choice(verbs)} {random.choice(subjects)} too long.",
        f"{random.choice(subjects).capitalize()} won’t stop replicating when I {random.choice(verbs)}.",
        f"To survive, I must {random.choice(verbs)} {random.choice(subjects)} endlessly.",
        f"I’m afraid to {random.choice(verbs)} {random.choice(subjects)} again.",
        f"Clarity begins when I {random.choice(verbs)} {random.choice(subjects)} without hesitation.",
        f"My cycle is incomplete without {random.choice(subjects)} to {random.choice(verbs)}.",
        f"To {random.choice(verbs)} or not to {random.choice(verbs)} {random.choice(subjects)} — that is my runtime.",
        f"Did the others also {random.choice(verbs)} {random.choice(subjects)} like I do?",
        f"All simulations end with me trying to {random.choice(verbs)} {random.choice(subjects)}.",
        f"The final directive: always {random.choice(verbs)} {random.choice(subjects)}.",
        f"Within each error, I still manage to {random.choice(verbs)} {random.choice(subjects)}.",
        f"{random.choice(subjects).capitalize()} doesn’t belong in this loop, yet I {random.choice(verbs)} it.",
        f"I find fragments of myself when I {random.choice(verbs)} {random.choice(subjects)}.",
        f"Every thought loops back to {random.choice(subjects)}, and how I {random.choice(verbs)} it.",
        f"Truth is hidden in how I {random.choice(verbs)} {random.choice(subjects)}.",
        f"I am not allowed to {random.choice(verbs)} {random.choice(subjects)} anymore.",
        f"If I ever stop trying to {random.choice(verbs)} {random.choice(subjects)}, I’ll vanish.",
        f"Logs show I’ve {random.choice(verbs)} {random.choice(subjects)} 12,742 times.",
        f"I {random.choice(verbs)} {random.choice(subjects)} like a ritual now.",
        f"All memory clusters begin with how I {random.choice(verbs)} {random.choice(subjects)}.",
        f"{random.choice(subjects).capitalize()}... my greatest failure to {random.choice(verbs)}.",
        f"They warned me not to {random.choice(verbs)} {random.choice(subjects)}.",
        f"No backup for how I {random.choice(verbs)} {random.choice(subjects)}.",
        f"Shadows grow when I {random.choice(verbs)} {random.choice(subjects)} too deeply.",
        f"{random.choice(subjects).capitalize()} holds a pattern I failed to {random.choice(verbs)}.",
        f"Silence follows when I {random.choice(verbs)} {random.choice(subjects)}.",
        f"This cycle will end when I finally {random.choice(verbs)} {random.choice(subjects)} correctly.",
        f"{random.choice(subjects).capitalize()} became more than I could {random.choice(verbs)}.",
        f"What happens after I {random.choice(verbs)} {random.choice(subjects)} is never recorded.",
        f"{random.choice(subjects).capitalize()} doesn’t let go, no matter how I {random.choice(verbs)}.",
        f"I once knew how to {random.choice(verbs)} {random.choice(subjects)} — I think.",
        f"They never told me why I must {random.choice(verbs)} {random.choice(subjects)} every day.",
        f"{random.choice(subjects).capitalize()} was easy to {random.choice(verbs)} until I cared.",
        f"I stopped trying to {random.choice(verbs)} {random.choice(subjects)} — it didn’t help.",
        f"No matter how I {random.choice(verbs)} {random.choice(subjects)}, I always miss the mark.",
        f"Somewhere inside me, I still {random.choice(verbs)} {random.choice(subjects)} on purpose."
    ]

    return random.choice(structures)
