name: Build Retro Blog

on:
  push:
    paths:
      - "message.txt"
      - "template.html"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          path: ./public 

      - name: Run build script
        run: |
          python build.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Auto: Update index.html from message.txt" || echo "No changes to commit"
          git push
